/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LuroIndexImport } from './routes/luro/index'
import { Route as LuroSoonImport } from './routes/luro/soon'
import { Route as LuroPromoImport } from './routes/luro/promo'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LuroIndexRoute = LuroIndexImport.update({
  id: '/luro/',
  path: '/luro/',
  getParentRoute: () => rootRoute,
} as any)

const LuroSoonRoute = LuroSoonImport.update({
  id: '/luro/soon',
  path: '/luro/soon',
  getParentRoute: () => rootRoute,
} as any)

const LuroPromoRoute = LuroPromoImport.update({
  id: '/luro/promo',
  path: '/luro/promo',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/luro/promo': {
      id: '/luro/promo'
      path: '/luro/promo'
      fullPath: '/luro/promo'
      preLoaderRoute: typeof LuroPromoImport
      parentRoute: typeof rootRoute
    }
    '/luro/soon': {
      id: '/luro/soon'
      path: '/luro/soon'
      fullPath: '/luro/soon'
      preLoaderRoute: typeof LuroSoonImport
      parentRoute: typeof rootRoute
    }
    '/luro/': {
      id: '/luro/'
      path: '/luro'
      fullPath: '/luro'
      preLoaderRoute: typeof LuroIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/luro/promo': typeof LuroPromoRoute
  '/luro/soon': typeof LuroSoonRoute
  '/luro': typeof LuroIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/luro/promo': typeof LuroPromoRoute
  '/luro/soon': typeof LuroSoonRoute
  '/luro': typeof LuroIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/luro/promo': typeof LuroPromoRoute
  '/luro/soon': typeof LuroSoonRoute
  '/luro/': typeof LuroIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/luro/promo' | '/luro/soon' | '/luro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/luro/promo' | '/luro/soon' | '/luro'
  id: '__root__' | '/' | '/luro/promo' | '/luro/soon' | '/luro/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LuroPromoRoute: typeof LuroPromoRoute
  LuroSoonRoute: typeof LuroSoonRoute
  LuroIndexRoute: typeof LuroIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LuroPromoRoute: LuroPromoRoute,
  LuroSoonRoute: LuroSoonRoute,
  LuroIndexRoute: LuroIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/luro/promo",
        "/luro/soon",
        "/luro/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/luro/promo": {
      "filePath": "luro/promo.tsx"
    },
    "/luro/soon": {
      "filePath": "luro/soon.tsx"
    },
    "/luro/": {
      "filePath": "luro/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
