query LuroWinner($address: Bytes, $round: BigInt) {
    winnerCalculateds(where: { address: $address, round: $round }) {
        winner
        winnerOffset
        transactionHash
        round
        bet
    }
}

query LuroWinners($address: Bytes) {
    winnerCalculateds(where: { address: $address }, first: 100, orderBy: round, orderDirection: desc) {
        winner
        winnerOffset
        transactionHash
        round
        bet
    }
}


query LuroRounds($address: Bytes) {
    rounds(where: { address: $address }, orderBy: round, orderDirection: desc) {
        round
        address
        betsAmount
        betsCount
        winnerAddress
        winnerOffset
    }
}

query LuroRoundsByPlayer($address: Bytes, $player: Bytes) {
    rounds(where: {address: $address, bets_: {player: $player}}, orderBy: round, orderDirection: desc) {
        round
        address
        betsAmount
        betsCount
        winnerAddress
        winnerOffset
    }
}