name: Build and Deploy

on:
  push:
    branches:
      - prod/*
permissions:
  actions: write
  contents: write
  pull-requests: write
  packages: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20

jobs:
  check-ipfs-disabled:
    environment: ${{ github.ref_name }}
    name: Check if IPFS is disabled
    runs-on: ubuntu-latest
    outputs:
      ipfs-disabled: ${{ steps.check.outputs.disabled }}
    steps:
      - name: Check IPFS variable
        id: check
        run: |
          if [ "${{ vars.IPFS }}" = "false" ]; then
            echo "disabled=true" >> $GITHUB_OUTPUT
            echo "IPFS is disabled, running regular build"
          else
            echo "disabled=false" >> $GITHUB_OUTPUT
            echo "IPFS is enabled, skipping regular build"
          fi

  setup:
    name: Setup and Build
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs: check-ipfs-disabled
    if: ${{ needs.check-ipfs-disabled.outputs.ipfs-disabled == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if build is needed
        id: check-build
        if: ${{ vars.IPFS == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch variables
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,${{ secrets.AWS_ENVIRONMENT }}
            ,${{ github.ref_name }}
          parse-json-secrets: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@betfinio"
          bun-version: latest

      - name: Install dependencies
        run: bun install
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          PUBLIC_OUTPUT_URL: https://${{secrets.AWS_BUCKET}}
          PUBLIC_BRANCH: ${{ github.ref_name }}
          PUBLIC_DEPLOYED: ${{ github.sha }}
        run: bun run build --env-mode ${{ secrets.AWS_ENVIRONMENT }}

      - name: Deploy to S3
        run: aws s3 cp ./dist s3://${{secrets.AWS_BUCKET}} --cache-control 'public, max-age=0' --recursive

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}} --paths '/*'
